logging:
    level:
#        tk.mybatis: DEBUG
        com.ooops.servant: DEBUG
spring:
    application:
        name: ooops
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    # 上传文件总的最大值
    servlet:
        multipart.max-request-size: 10MB
        multipart.max-file-size: 10MB
    datasource:
        name: test 
        url: jdbc:mysql://localhost:3306/servant?useUnicode=true&characterEncoding=UTF8
        username: root
        password: 123456
        # 使用druid数据源
#        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    thymeleaf:
        cache: false

mybatis:
    basepackage: com.ooops.servant.mapper
    xmlLocation: classpath:mapper/**/*.xml
    mapper-locations: "classpath*:mapper/*.xml"

server:
    port: 80
    session:
        timeout: 43200
    
upload:
#    path: D:/fileRoot/
    path: /home/devilkxh/files/